type = "module"
modules = [ "sample_module_id",]
id = "sample_module_id"
name = "module name"
version = "0.0.0"
versionCode = 25040501
description = "sample"
author = "LIghtJUNction"
updateJson = "https://raw.githubusercontent.com/LIghtJUNction/aivk-module-sample/main/update.json"
license = "MIT"
startMode = "import"
dependencies = []
