type = "module" # or "modules"
modules = ['moduleID'] # if type is "modules", this should be a list of module IDs 

# if type is "module": 
id="sampleModuleID" # module ID, should be unique in the system
name="Sample Module" # updated name for clarity
version="0.1.0" # version of the module
versionCode=25040301 # unique version code
description="sample" # description of the module
author="LIghtJUNction" # author of the module
updateJson="https://.../update.json" # URL for update information
license="MIT" # license type

# - import: 作为模块导入(在同一进程中运行) 建议核心模块使用此模式 方便通信
# - process: 在独立进程中启动 建议非核心模块使用此模式 方便调试和隔离 可以使用独立的python环境
startMode="import"

dependencies = [
]
# "moduleID:>=0.1.0" # moduleID:>=0.1.0 or :== :<= :>= :<= :!=