name: Package and Release Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 0.1.0)'
        required: true
      changelog:
        description: '更新日志 (留空则自动使用 CHANGELOG.MD 中的内容)'
        required: false
      skip_executables:
        description: '跳过构建可执行文件'
        required: false
        default: false
        type: boolean
      skip_dependencies:
        description: '跳过刷新依赖'
        required: false
        default: false
        type: boolean

jobs:
  package:
    runs-on: ubuntu-latest
    # 添加权限设置
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 获取完整历史以确保不会发生冲突
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml python-dateutil pyinstaller
          pip install uv

      - name: Package module
        id: package
        run: |
          # 准备参数
          ARGS=""
          if [ "${{ github.event.inputs.changelog }}" != "" ]; then
            ARGS="${ARGS} --changelog \"${{ github.event.inputs.changelog }}\""
          fi
          
          if [ "${{ github.event.inputs.skip_executables }}" == "true" ]; then
            ARGS="${ARGS} --skip-executables"
          fi
          
          if [ "${{ github.event.inputs.skip_dependencies }}" == "true" ]; then
            ARGS="${ARGS} --skip-dependencies"
          fi
          
          # 运行打包脚本
          python .github/scripts/package_module.py --version "${{ github.event.inputs.version }}" ${ARGS}
          
          # 设置输出
          echo "::set-output name=module_id::$(cat meta.toml | grep id | head -1 | cut -d'"' -f2)"
        
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit changes
        run: |
          git add meta.toml update.json CHANGELOG.MD
          git add bin/ || echo "No bin directory to add"
          git commit -m "Release version ${{ github.event.inputs.version }}"
      
      - name: Create tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
          
      - name: Push changes and tags
        # 使用内置的 Git 命令推送更改，避免使用第三方 Action
        run: |
          git push origin HEAD:${{ github.ref }} --force
          git push origin --tags --force
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ env.CHANGELOG || steps.package.outputs.changelog || github.event.inputs.changelog || format('版本 {0} 发布', github.event.inputs.version) }}
          draft: false
          prerelease: false
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}