name: Package and Release Module

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 0.1.0)'
        required: true
      changelog:
        description: '更新日志'
        required: true

jobs:
  package:
    runs-on: ubuntu-latest
    # 添加权限设置
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 获取完整历史以确保不会发生冲突
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml python-dateutil

      - name: Package module
        id: package
        run: |
          python .github/scripts/package_module.py \
            --version "${{ github.event.inputs.version }}" \
            --changelog "${{ github.event.inputs.changelog }}"
        
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit changes
        run: |
          git add meta.toml update.json
          git commit -m "Release version ${{ github.event.inputs.version }}"
      
      - name: Create tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Version ${{ github.event.inputs.version }}"
          
      - name: Push changes and tags
        # 使用内置的 Git 命令推送更改，避免使用第三方 Action
        run: |
          git push origin HEAD:${{ github.ref }} --force
          git push origin --tags --force
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.changelog }}
          draft: false
          prerelease: false
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}